/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 4
        max_iteration: 3
        filter_size_surf: 0.5
        filter_size_map: 0.5
        cube_side_length: 1000.0
        runtime_pos_log_enable: false
        map_file_path: "./test.pcd"

        common:
            lid_topic:  "/velodyne_points"
            imu_topic:  "/imu"
            time_sync_en: false
            time_offset_lidar_to_imu: 0.0

        preprocess:
            lidar_type: 4                # is set to general pointcloud input
            scan_line: 16                # needs to be adjusted depending on lidar scan line number
            scan_rate: 10
            timestamp_unit: 2            # micro sec unit
            blind: 0.1

        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree: 360.0
            det_range: 100.0
            extrinsic_est_en: false
            extrinsic_T: [0.0, 0.0, 0.1]
            extrinsic_R: [1.0, 0.0, 0.0,
                         0.0, 1.0, 0.0,
                         0.0, 0.0, 1.0]

        publish:
            path_en: true                # path topic publish activated
            scan_publish_en: true
            dense_publish_en: true
            scan_bodyframe_pub_en: true

        pcd_save:
            pcd_save_en: true
            interval: -1
